version: "3"
services:
  postgres_db:
    image: postgres:11
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_app:
    image: python:3.8
    build: 
      context: ./python_app/
      dockerfile: Dockerfile
    environment:
      -  POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      -  POSTGRES_DB=${POSTGRES_DB}
      -  POSTGRES_USER=${POSTGRES_USER}
      -  POSTGRES_PORT=${POSTGRES_PORT}
      -  POSTGRES_HOST=${POSTGRES_HOST}
      -  POSTGRES_TABLE_NAME=${POSTGRES_TABLE_NAME}
      -  IMAGE_SAMPLE_SIZE=${IMAGE_SAMPLE_SIZE}
      -  IMAGES_S3_LOCATION=${IMAGES_S3_LOCATION}
    depends_on:
      - postgres_db
    container_name: 
      ${CONTAINER_NAME}
